id: PBE9F2A44
initial_creation_type: ocr
source_metadata:
  volumes:
    de44934c89dd4aadbf1befba96d48040:
      base_file: v056.txt
      image_group_id: I1PD95901
      title: བཅོམ་ལྡན་འདས་མ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་སྙིང་པོའི་འགྲེལ་པ་དོན་གྱི་སྒྲོན་མ།
      total_pages: 1682
      volume_number: 56
