id: D4FF78E49
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-27T08:25:29+00:00'
last_modified: '2022-05-27T05:33:34.333192+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    3bbb:
      image_group_id: I1PD95901
      title: བཅོམ་ལྡན་འདས་མ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་སྙིང་པོའི་འགྲེལ་པ་དོན་གྱི་སྒྲོན་མ།
      total_pages: 1682
      order: 56
      base_file: 3bbb.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
